import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/header/Header";
import Smoothscroll from "@/lib/Smoothscroll";
import FooterBanner from "@/components/Footer/FooterBanner";
import { SanityLive } from "@/sanity/live";
import ClickSpark from "@/components/ReactBit/ClickSpark/ClickSpart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Phone Lynn Thant",
  description: "Generated by Ye Myint Kyaw",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-secondary text-primary`}>
        
        <Header/>
        <Smoothscroll>
          <div id="smooth-wrapper">
            <div id="smooth-content">
              <ClickSpark
                sparkColor='#1b1b1b'
                sparkSize={10}
                sparkRadius={15}
                sparkCount={8}
                duration={400}
              >
                {children}
              </ClickSpark>
              <Footer/>
            </div>
          </div>
        </Smoothscroll>
        <FooterBanner/>

        <SanityLive/>
      </body>
    </html>
  );
}
