import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/scss/style.scss";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Designer Portfolio",
  description: "Generated by Ye Myint Kyaw",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
